export const HOMEPAGE_FETCH_RESTO_START = 'HOMEPAGE_FETCH_RESTO_START';
export const HOMEPAGE_FETCH_RESTO_SUCCESS = 'HOMEPAGE_FETCH_RESTO_SUCCESS';
export const HOMEPAGE_FETCH_RESTO_FAILED = 'HOMEPAGE_FETCH_RESTO_FAILED';

export const DETAILS_FETCH_RESTO_START = 'DETAILS_FETCH_RESTO_START';
export const DETAILS_FETCH_RESTO_SUCCESS = 'DETAILS_FETCH_RESTO_SUCCESS';
export const DETAILS_FETCH_RESTO_FAIL = 'DETAILS_FETCH_RESTO_FAIL';

export const HOMEPAGESIGNED_FETCH_RESTO_START = 'HOMEPAGESIGNED_FETCH_RESTO_START';
export const HOMEPAGESIGNED_FETCH_RESTO_SUCCESS = 'HOMEPAGESIGNED_FETCH_RESTO_SUCCESS';
export const HOMEPAGESIGNED_FETCH_RESTO_FAILED = 'HOMEPAGESIGNED_FETCH_RESTO_FAILED';