export const HOMEPAGE_FETCH_RESTO_START = 'HOMEPAGE_FETCH_RESTO_START';
export const HOMEPAGE_FETCH_RESTO_SUCCESS = 'HOMEPAGE_FETCH_RESTO_SUCCESS';
export const HOMEPAGE_FETCH_RESTO_FAILED = 'HOMEPAGE_FETCH_RESTO_FAILED';
